version: '3.0'
services:
  app:
    image: cliente-productividad
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    networks:
      - productividadNetwork

networks:
  productividadNetwork: